workflows:
  react-native-android:
    name: React Native Android Workflow
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 16.10.0
        JAVA_VERSION: 11
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
